-- what is the total revenue generated by male and female -- 

SELECT gender, SUM(purchase_amount) AS revenue
FROM customer_details
GROUP BY gender;


-- Which customer used a discount but still spent more than avereage purchase -- 

SELECT customer_id, purchase_amount, discount_applied
FROM customer_details
WHERE discount_applied = "Yes" AND purchase_amount >= (SELECT AVG(purchase_amount) from customer_details)


-- Which are the top 5 products with the highest average review rating ? -- 

SELECT item_purchased, ROUND(AVG(review_rating),2) AS avg_review_rating
FROM customer_details
GROUP BY item_purchased
ORDER BY avg_review_rating DESC
LIMIT 5;


-- Compare the average purchase amounts between Standard and Express shipping -- 

SELECT shipping_type, ROUND(AVG(purchase_amount),2)
FROM customer_details
WHERE shipping_type IN ("Express", "Standard")
GROUP BY shipping_type;


-- Do suscribers customers spend more ? compare avg and total revenue between  subscribers and non-subscriberes -- 

SELECT subscription_status, COUNT(customer_id) as total_customer, ROUND(AVG(purchase_amount),2) AS avg_amount, SUM(purchase_amount) AS total_amount
FROM customer_details
GROUP BY subscription_status;


-- Which 5 products have the highest percentage of purcases with discounts applied? -- 

SELECT item_purchased, COUNT(item_purchased),
ROUND(SUM(CASE WHEN discount_applied = "YES" THEN 1 ELSE 0 END)/COUNT(*) * 100, 2) AS discount_rate
FROM customer_details
GROUP BY item_purchased
ORDER BY discount_rate DESC
LIMIT 5;


-- Segment customers into New, Returning, and Loyal based on their total number of previous purchases, and show the count of each segment. -- 

WITH customer_appearence AS
(
SELECT previous_purchases,
CASE
	WHEN previous_purchases = 1 THEN "New"
	WHEN previous_purchases BETWEEN 2 AND 10 THEN "Returning"
	ELSE "Loyal"
END AS customer_segment
FROM customer_details
)
SELECT customer_segment, COUNT(*) AS no_of_customer
FROM customer_appearence
GROUP BY customer_segment;


-- What are the top 3 most purchased products within each category? -- 

WITH item_order AS
(
SELECT item_purchased,
category,
COUNT(customer_id) AS total_orders, 
ROW_NUMBER() OVER(PARTITION BY category ORDER BY COUNT(customer_id) DESC) AS item_rank
FROM customer_details
GROUP BY category, item_purchased
)
SELECT category, item_purchased, total_orders
FROM item_order
WHERE item_rank <= 3;


-- Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe? --  

SELECT COUNT(customer_id) AS repeat_buyers, subscription_status
FROM customer_details
WHERE previous_purchases > 5
GROUP BY subscription_status;


-- What is the revenue contribution of each age group? --  


SELECT SUM(purchase_amount) AS total_revenue, age_group
FROM customer_details
GROUP BY age_group
ORDER BY SUM(purchase_amount) DESC;


